import { Customer } from "./types/customerTableTypes";

export const CustomerData: Customer[] = [
  {
    name: "Anshul Trading Company",
    customerId: 1000,
    totalInvoices: 212,
    outstandingAmount: "₹600",
    overdueInvoices: 212,
    overdueAmount: 100,
    creditDebitNote: "Yes",
    invoices: [
      {
        invoiceId: "IN1718000000492024001",
        invoiceNumber: "IN1718000000492024",
        customerName: "Anshul trading Company",
        invoiceDate: "",
        outstandingAmount: 100,
        dueDate: "7/10/33",
        status: null,
        lastReminder: "25/09/24",
        invoiceAmount: "0.00",
        discount: "0.00",
        region: null,
        division: "",
        documentType: "DEBIT_NOTE",
        documentNumber: "",
        additionalInfo: [
          {
            label: "Region",
            value: "Tamil Nadu",
            sequence: 1,
          },
          {
            label: "Location",
            value: "",
            sequence: 2,
          },
        ],
      },
      {
        invoiceId: "IN1718000000142017001",
        invoiceNumber: "IN1718000000142017",
        customerName: "Anshul trading Company",
        invoiceDate: "",
        outstandingAmount: 200,
        dueDate: "07/02/28",
        status: null,
        lastReminder: "06/09/24",
        additionalInfo: [
          {
            label: "Region",
            value: "Tamil Nadu",
            sequence: 1,
          },
          {
            label: "Location",
            value: "",
            sequence: 2,
          },
        ],
        invoiceAmount: "",
        discount: "",
        region: null,
        division: "",
        documentType: "",
        documentNumber: "",
      },
      {
        invoiceId: "IN1718000000432024001",
        invoiceNumber: "IN1718000000432024",
        customerName: "Anshul trading Company",
        invoiceDate: "",
        outstandingAmount: 300,
        dueDate: "18/04/23",
        status: null,
        lastReminder: "06/09/24",
        additionalInfo: [
          {
            label: "Region",
            value: "Tamil Nadu",
            sequence: 1,
          },
          {
            label: "Location",
            value: "",
            sequence: 2,
          },
        ],
        invoiceAmount: "",
        discount: "",
        region: null,
        division: "",
        documentType: "",
        documentNumber: "",
      },
    ],
  },
  {
    name: "Omega Glass Private Limited",
    customerId: 388,
    totalInvoices: 5,
    outstandingAmount: "₹900",
    overdueInvoices: 5,
    overdueAmount: 200,
    creditDebitNote: "No",
    invoices: [
      {
        invoiceId: "IN1718000000142017002",
        invoiceNumber: "IN1714000016402024",
        documentDetails: "IN • 0090037560",
        invoiceDate: "22/04/24",
        outstandingAmount: 400,
        dueDate: "22/04/23",
        status: "Overdue by 158 days",
        lastReminder: "27/09/24",
        customerName: "Omega Glass Private Limited",
        invoiceAmount: "",
        discount: "",
        region: null,
        division: "",
        documentType: "",
        documentNumber: "",
      },
      {
        invoiceId: "IN1718000000142017003",
        invoiceNumber: "IN1714000016402024",
        documentDetails: "IN • 0090037560",
        invoiceDate: "22/04/24",
        outstandingAmount: 500,
        dueDate: "22/04/30",
        status: "Overdue by 158 days",
        lastReminder: "27/09/24",
        customerName: "Omega Glass Private Limited",
        invoiceAmount: "",
        discount: "",
        region: null,
        division: "",
        documentType: "",
        documentNumber: "",
      },
    ],
  },
  {
    name: "RAJEEV  & ENTERPRISES",
    customerId: 387,
    totalInvoices: 1,
    overdueInvoices: 1,
    overdueAmount: 50000.0,
    outstandingAmount: "50000.00",
    creditDebitNote: "No",
    invoices: [
      {
        invoiceId: "IN1714000016472024001",
        invoiceNumber: "IN1714000016472024",
        customerName: "RAJEEV  & ENTERPRISES",
        invoiceDate: "23/04/24",
        outstandingAmount: 50000.0,
        dueDate: "23/04/24",
        status: null,
        lastReminder: "06/09/24",
        invoiceAmount: "0.00",
        discount: "0.00",
        region: null,
        division: "I1",
        documentType: "INVOICE",
        documentNumber: "0090037568",
        additionalInfo: [
          {
            label: "Region",
            value: "West Bengal",
            sequence: 1,
          },
          {
            label: "Location",
            value: "Media",
            sequence: 2,
          },
        ],
      },
    ],
  },
  {
    name: "GLOWWELL SIGN",
    customerId: 392,
    totalInvoices: 1,
    overdueInvoices: 1,
    overdueAmount: 50000.0,
    outstandingAmount: "50000.00",
    creditDebitNote: "No",
    invoices: [
      {
        invoiceId: "IN1714000016452024001",
        invoiceNumber: "IN1714000016452024",
        customerName: "GLOWWELL SIGN",
        invoiceDate: "22/04/24",
        outstandingAmount: 50000.0,
        dueDate: "20/08/24",
        status: null,
        lastReminder: "31/07/24",
        invoiceAmount: "0.00",
        discount: "0.00",
        region: null,
        division: "I2",
        documentType: "INVOICE",
        documentNumber: "0090037565",
        additionalInfo: [
          {
            label: "Region",
            value: "Gujarat",
            sequence: 1,
          },
          {
            label: "Location",
            value: "Telco",
            sequence: 2,
          },
        ],
      },
    ],
  },
  {
    name: "MANOJ AUTO MOBILES",
    customerId: 393,
    totalInvoices: 1,
    overdueInvoices: 1,
    overdueAmount: 50000.0,
    outstandingAmount: "50000.00",
    creditDebitNote: "No",
    invoices: [
      {
        invoiceId: "IN1714000016462024001",
        invoiceNumber: "IN1714000016462024",
        customerName: "MANOJ AUTO MOBILES",
        invoiceDate: "22/04/24",
        outstandingAmount: 50000.0,
        dueDate: "20/08/24",
        status: null,
        lastReminder: "29/07/24",
        invoiceAmount: "0.00",
        discount: "0.00",
        region: null,
        division: "I2",
        documentType: "INVOICE",
        documentNumber: "0090037566",
        additionalInfo: [
          {
            label: "Region",
            value: "Orissa",
            sequence: 1,
          },
          {
            label: "Location",
            value: "Telco",
            sequence: 2,
          },
        ],
      },
    ],
  },
  {
    name: "Ramprasad and center",
    customerId: 100186,
    totalInvoices: 1,
    overdueInvoices: 1,
    overdueAmount: 10102.00,
    outstandingAmount: "10102.00",
    creditDebitNote: "No",
    invoices: [
      {
        invoiceId: "IN1714000016522024001",
        invoiceNumber: "IN1714000016522024",
        customerName: "Ramprasad and center",
        invoiceDate: "23/04/24",
        outstandingAmount: 10102.00,
        dueDate: "23/04/24",
        status: null,
        lastReminder: "23/07/24",
        invoiceAmount: "0.00",
        discount: "0.00",
        region: null,
        division: "I2",
        documentType: "INVOICE",
        documentNumber: "0090037581",
        additionalInfo: [
          {
            label: "Region",
            value: "Telangana",
            sequence: 1,
          },
          {
            label: "Location",
            value: "Telco",
            sequence: 2,
          },
        ],
      },
    ],
  },
  {
    name: "New Pharma company",
    customerId: 100196,
    totalInvoices: 1,
    overdueInvoices: 1,
    overdueAmount: 10000.00,
    outstandingAmount: "10000.00",
    creditDebitNote: "No",
    invoices: [
      {
        invoiceId: "IN1714000016512024001",
        invoiceNumber: "IN1714000016512024",
        customerName: "New Pharma company",
        invoiceDate: "23/04/24",
        outstandingAmount: 10000.00,
        dueDate: "23/04/24",
        status: null,
        lastReminder: "23/07/24",
        invoiceAmount: "0.00",
        discount: "0.00",
        region: null,
        division: "I1",
        documentType: "INVOICE",
        documentNumber: "0090037579",
        additionalInfo: [
          {
            label: "Region",
            value: "Delhi",
            sequence: 1,
          },
          {
            label: "Location",
            value: "Media",
            sequence: 2,
          },
        ],
      },
    ],
  },
  {
    name: "SHILPI BATH DCOS & distributor",
    customerId: 394,
    totalInvoices: 386,
    overdueInvoices: 386,
    overdueAmount: -524672326.11,
    outstandingAmount: "-524672326.11",
    creditDebitNote: "Yes",
    invoices: [
      {
        invoiceId: "IN1718000000482024001",
        invoiceNumber: "IN1718000000482024",
        customerName: "SHILPI BATH DCOS & distributor",
        invoiceDate: "",
        outstandingAmount: 99999999.00,
        dueDate: "17/06/24",
        status: null,
        lastReminder: "31/07/24",
        invoiceAmount: "0.00",
        discount: "0.00",
        region: null,
        division: "",
        documentType: "DEBIT_NOTE",
        documentNumber: "",
        additionalInfo: [
          {
            label: "Region",
            value: "Haryana",
            sequence: 1,
          },
          {
            label: "Location",
            value: "",
            sequence: 2,
          },
        ],
      },
      {
        invoiceId: "IN1714000009362019002",
        invoiceNumber: "IN1714000009362019",
        customerName: "SHILPI BATH DCOS & distributor",
        invoiceDate: "",
        outstandingAmount: 800200.00,
        dueDate: "17/01/20",
        status: null,
        lastReminder: "31/07/24",
        invoiceAmount: "0.00",
        discount: "0.00",
        region: null,
        division: "",
        documentType: "DEBIT_NOTE",
        documentNumber: "",
        additionalInfo: [
          {
            label: "Region",
            value: "Haryana",
            sequence: 1,
          },
          {
            label: "Location",
            value: "",
            sequence: 2,
          },
        ],
      },
    ],
  },
  {
    name: "SCOPE & VINTRADE",
    customerId: 389,
    totalInvoices: 166,
    overdueInvoices: 166,
    overdueAmount: -5695223766.00,
    outstandingAmount: "-5695223766.00",
    creditDebitNote: "No",
    invoices: [
      {
        invoiceId: "IN1714000011972021001",
        invoiceNumber: "IN1714000011972021",
        customerName: "SCOPE & VINTRADE",
        invoiceDate: "",
        outstandingAmount: -1.00,
        dueDate: "12/07/21",
        status: null,
        lastReminder: "29/07/24",
        invoiceAmount: "0.00",
        discount: "0.00",
        region: null,
        division: "",
        documentType: "CREDIT_NOTE",
        documentNumber: "",
        additionalInfo: [
          {
            label: "Region",
            value: "West Bengal",
            sequence: 1,
          },
          {
            label: "Location",
            value: "",
            sequence: 2,
          },
        ],
      },
      {
        invoiceId: "IN1714000012182021001",
        invoiceNumber: "IN1714000012182021",
        customerName: "SCOPE & VINTRADE",
        invoiceDate: "",
        outstandingAmount: -1.00,
        dueDate: "13/07/21",
        status: null,
        lastReminder: null,
        invoiceAmount: "0.00",
        discount: "0.00",
        region: null,
        division: "",
        documentType: "CREDIT_NOTE",
        documentNumber: "",
        additionalInfo: [
          {
            label: "Region",
            value: "West Bengal",
            sequence: 1,
          },
          {
            label: "Location",
            value: "",
            sequence: 2,
          },
        ],
      },
    ],
  },
];
